const columns = [
    {name: "CLUBE", uid: "name"},
    {name: "LIGA E NAÇÃO", uid: "league"},
  ];
  
  const pote1 = [
    {
      id: 1,
      name: "Real Madrid",
      league: "La Liga",
      nation: "Espanha",
      avatar: "realmadrid.svg",
    },
    {
      id: 2,
      name: "Manchester City",
      league: "Premier League",
      nation: "Inglaterra",
      avatar: "mancity.svg",
    },
    {
      id: 3,
      name: "Bayern Munique",
      league: "Bundesliga",
      nation: "Alemanha",
      avatar: "bayern.svg",
    },
    {
      id: 4,
      name: "Paris Saint-Germain",
      league: "Ligue 1",
      nation: "França",
      avatar: "psg.svg",
    },
    {
      id: 5,
      name: "Liverpool",
      league: "Premier League",
      nation: "Inglaterra",
      avatar: "liverpool.svg",
    },
    {
        id: 6,
        name: "Inter",
        league: "Serie A",
        nation: "Italia",
        avatar: "inter.svg",
      },
      {
        id: 7,
        name: "Borussia Dortmund",
        league: "Bundesliga",
        nation: "Alemanha",
        avatar: "borussiadortmund.svg",
      },
      {
        id: 8,
        name: "RB Leipzig",
        league: "Bundesliga",
        nation: "Alemanha",
        avatar: "rbleipzig.svg",
      },
      {
        id: 9,
        name: "Barcelona",
        league: "La Liga",
        nation: "Espanha",
        avatar: "barcelona.svg",
      },
  ];

  const pote2 = [
    {
      id: 1,
      name: "Bayer Leverkusen",
      league: "Bundesliga",
      nation: "Alemanha",
      avatar: "bayerleverkusen.svg",
    },
    {
      id: 2,
      name: "Atlético de Madrid",
      league: "La Liga",
      nation: "Espanha",
      avatar: "atleticomadrid.svg",
    },
    {
      id: 3,
      name: "Atalanta",
      league: "Serie A",
      nation: "Italia",
      avatar: "atalanta.svg",
    },
    {
      id: 4,
      name: "Juventus",
      league: "Serie A",
      nation: "Italia",
      avatar: "juventus.svg",
    },
    {
      id: 5,
      name: "Benfica",
      league: "Liga Portugal",
      nation: "Portugal",
      avatar: "benfica.svg",
    },
    {
      id: 6,
      name: "Arsenal",
      league: "Premier League",
      nation: "Inglaterra",
      avatar: "arsenal.svg",
    },
    {
        id: 7,
        name: "Club Brugge",
        league: "Belgian Pro League",
        nation: "Belgica",
        avatar: "clubbrugge.svg",
      },
      {
        id: 8,
        name: "Shakhtar Donetsk",
        league: "Ukranian Premier League",
        nation: "Ucrania",
        avatar: "shakhtar.svg",
      },
      {
        id: 9,
        name: "Milan",
        league: "Serie A",
        nation: "Italia",
        avatar: "acmilan.svg",
      },
  ];

  const pote3 = [
    {
      id: 1,
      name: "Feynoord",
      league: "Eredivise",
      nation: "Holanda",
      avatar: "feyenoord.svg",
    },
    {
      id: 2,
      name: "Sporting",
      league: "Liga Portugesa",
      nation: "Portugal",
      avatar: "sporting.svg",
    },
    {
      id: 3,
      name: "PSV",
      league: "Eredivise",
      nation: "Holanda",
      avatar: "psv.svg",
    },
    {
      id: 4,
      name: "Dinamo",
      league: "Croatian Football League",
      nation: "Croacia",
      avatar: "dinamozagreb.svg",
    },
    {
      id: 5,
      name: "Salzburgo",
      league: "Austrian Bundesliga",
      nation: "Austria",
      avatar: "redbullsalzburg.svg",
    },
    {
      id: 6,
      name: "Lille",
      league: "Ligue 1",
      nation: "França",
      avatar: "lille.svg",
    },
    {
        id: 7,
        name: "Estrela Vermelha",
        league: "Russian Super League",
        nation: "Belgium",
        avatar: "crvenazvezda.svg",
      },
      {
        id: 8,
        name: "Young Boys",
        league: "Swiss Super League",
        nation: "Suiça",
        avatar: "youngboys.svg",
      },
      {
        id: 9,
        name: "Celtic",
        league: "Scottish Premiership",
        nation: "Escócia",
        avatar: "celtic.svg",
      },
  ];

  const pote4 = [
    {
      id: 1,
      name: "Slovan Bratislava",
      league: "Slovak League",
      nation: "Eslováquia",
      avatar: "slovanbratislava.svg",
    },
    {
      id: 2,
      name: "Mónaco",
      league: "Ligue 1",
      nation: "França",
      avatar: "asmonaco.svg",
    },
    {
      id: 3,
      name: "Sparta Praga",
      league: "Czech First League",
      nation: "Chéquia",
      avatar: "spartapraha.svg",
    },
    {
      id: 4,
      name: "Aston Villa",
      league: "Premier League",
      nation: "Inglaterra",
      avatar: "astonvilla.svg",
    },
    {
      id: 5,
      name: "Bolonha",
      league: "Serie A",
      nation: "Italia",
      avatar: "bolognafc.svg",
    },
    {
      id: 6,
      name: "Girona",
      league: "La Liga",
      nation: "espanha",
      avatar: "girona.svg",
    },
    {
        id: 7,
        name: "Estugarda",
        league: "Bundesliga",
        nation: "Alemanha",
        avatar: "vfbstuttgart.svg",
      },
      {
        id: 8,
        name: "Sturm Graz",
        league: "Austrian Bundesliga",
        nation: "Austria",
        avatar: "sturmgraz.svg",
      },
      {
        id: 9,
        name: "Brest",
        league: "Ligue 1",
        nation: "França",
        avatar: "sb29.svg",
      },
  ];

  export { columns, users, pote1, pote2, pote3, pote4 };