export const users = [
    {
      key: "1",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "2",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "3",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "4",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "5",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "6",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "7",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "8",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "9",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "10",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "11",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "12",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "13",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "14",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "15",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "16",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "17",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "18",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "19",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "20",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "21",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "22",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "23",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "24",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "25",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "26",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "27",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "28",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "29",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "30",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "31",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "32",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "33",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "34",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "35",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
    {
      key: "36",
      avatar: "/realmadrid.svg",
      A1: "Manchester United",
      H1: "Benfica",
      A2: "Manchester United",
      H2: "Benfica",
      A3: "Manchester United",
      H3: "Benfica",
      A4: "Manchester United",
      H4: "Benfica",
    },
  ];